---
- name:  allowall and restart
  import_role:
    name: mongod
    tasks_from: install_mongod


- name:  reload and start
  import_role:
    name: common
    tasks_from: reload_start

- name:  allowall and restart
  import_role:
    name: mongod
    tasks_from: allowall_restart

