- name: create a file
  copy:
    content: |
              [mongodb-org-4.2]
              name=MongoDB Repository
              baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
              gpgcheck=0
              enabled=1
    dest: /etc/yum.repos.d/mongo.repo
- name: install mongodb required version
  dnf:
    name: mongodb-org
    state: present


- name:  reload and start
  import_role:
    name: common
    tasks_from: reload_start

- name:  allowall and restart
  import_role:
    name: mongod
    tasks_from: allowall_restart

