---
- name: install nodejs 18
  import_role:
    name: common
    tasks_from: nodejs

- name: download and installing dependencies
  import_role:
    name: common
    tasks_from: download_install

- name: configure service file
  import_role:
    name: catalogue
    tasks_from: catalogue_service
- name: reload catalogue.service
  import_role:
    name: common
    tasks_from: daemon_reload
- name:  reload and start
  import_role:
    name: common
    tasks_from: reload_start
- name:  reload and start
  import_role:
    name: common
    tasks_from: mongod_data_load
