- name: install nginx
  dnf:
    name: nginx
    state: present
- name: enable and start
  service:
    name: nginx
    enabled: yes
    state: started
- name: removing default html file
  file:
    path: /usr/share/nginx/html/*
    state: absent
- name: download frontend content
  get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp/web.zip
- name: Extract web.zip
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: configuration roboshop
  copy:
    content: |
          proxy_http_version 1.1;
          location /images/ {
            expires 5s;
            root   /usr/share/nginx/html;
            try_files $uri /images/placeholder.jpg;
          }
          location /api/catalogue/ { proxy_pass http://catalogue.hiteshshop.online:8080/; }
          location /api/user/ { proxy_pass http://user.hiteshshop.online:8080/; }
          location /api/cart/ { proxy_pass http://cart.hiteshshop.online:8080/; }
          location /api/shipping/ { proxy_pass http://shipping.hiteshshop.online:8080/; }
          location /api/payment/ { proxy_pass http://payment.hiteshshop.online:8080/; }

          location /health {
            stub_status on;
            access_log off;
          }
    dest: /etc/nginx/default.d/roboshop.conf 
- name: Enable and start "{{ component }}" service
  service:
    name: nginx
    enabled: yes
    state: restarted