---
- name: Download application code
  get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{ component }}.zip
    dest: /tmp/{{component}}.zip

- name: Extract application code
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: true

- name: Install '{{ component }}' dependencies
  npm:
    path: /app
  when: component in ['catalogue', 'user', 'cart']
  
- name: install '{{ component }}' dependencies
  shell: mvn clean package
  args:
    chdir: /app
  when: component == "shipping"

- name: install '{{ component }}' dependencies
  shell : pip3.6 install -r requirements.txt
  args:
    chdir: /app
  when: component == "payment"  

