- name: install mysql
  shell: dnf install mysql -y
- name: load data
  shell: mysql -h mysql.hiteshshop.online -uroot -pRoboShop@1 < /app/schema/shipping.sql 
- name: restart shipping
  service:
    state: restarted
    name: shipping