- name: install nodejs 18
  import_role:
    name: common
    tasks_from: nodejs

- name: download and installing dependencies
  import_role:
    name: common
    tasks_from: download_install
- name: configure user service
  import_role:
    name: cart
    tasks_from: cart_service
- name: reload cart.service
  import_role:
    name: common
    tasks_from: daemon_reload
- name:  reload and start
  import_role:
    name: common
    tasks_from: reload_start

